export const player = {
  stats: [1, 1, 1, 1, 1, 1, 1, 1, 10, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  stat_images: [
    "Attack_Icon.webp",
    "Strength_icon.webp",
    "Defence_Icon.webp",
    "Ranged_icon.png",
    "Prayer_icon.png",
    "Magic_icon.png",
    "Runecraft_Icon.png",
    "Construction_icon.png",
    "Hitpoints_icon.png",
    "Agility_icon.webp",
    "Herblore_icon.png",
    "Thieving_icon.png",
    "Crafting_icon.png",
    "Fletching_icon.png",
    "Slayer_icon.png",
    "Hunter_icon.png",
    "Mining_icon.png",
    "Smithing_Icon.png",
    "Fishing_Icon.png",
    "Cooking_icon.png",
    "Firemaking_icon.webp",
    "Woodcutting_icon.png",
    "Farming_icon.png",
  ],
};

export const skills = [
  {
    id: 1,
    skill_id: 0,
    max_level: 10,
    type: "skill",
    name: "Attack 10",
    image_name: "Attack_Icon.webp",
    isUnlocked: true,
    isComplete: false,
  },
  {
    id: 2,
    skill_id: 0,
    max_level: 20,
    type: "skill",
    name: "Attack 20",
    image_name: "Attack_Icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
  {
    id: 3,
    skill_id: 0,
    max_level: 30,
    type: "skill",
    name: "Attack 30",
    image_name: "Attack_Icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
  {
    id: 4,
    skill_id: 0,
    max_level: 40,
    type: "skill",
    name: "Attack 40",
    image_name: "Attack_Icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
  {
    id: 5,
    skill_id: 0,
    max_level: 50,
    type: "skill",
    name: "Attack 50",
    image_name: "Attack_Icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
  {
    id: 6,
    skill_id: 0,
    max_level: 60,
    type: "skill",
    name: "Attack 60",
    image_name: "Attack_Icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
  {
    id: 7,
    skill_id: 0,
    max_level: 70,
    type: "skill",
    name: "Attack 70",
    image_name: "Attack_Icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
  {
    id: 8,
    skill_id: 0,
    max_level: 80,
    type: "skill",
    name: "Attack 80",
    image_name: "Attack_Icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
  {
    id: 9,
    skill_id: 0,
    max_level: 90,
    type: "skill",
    name: "Attack 90",
    image_name: "Attack_Icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
  {
    id: 10,
    skill_id: 0,
    max_level: 95,
    type: "skill",
    name: "Attack 95",
    image_name: "Attack_Icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
  {
    id: 11,
    skill_id: 0,
    max_level: 99,
    type: "skill",
    name: "Attack 99",
    image_name: "Attack_Icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
  {
    id: 12,
    skill_id: 1,
    max_level: 10,
    type: "skill",
    name: "Strength 10",
    image_name: "Strength_icon.webp",
    isUnlocked: true,
    isComplete: false,
  },
  {
    id: 13,
    skill_id: 1,
    max_level: 20,
    type: "skill",
    name: "Strength 20",
    image_name: "Strength_icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
  {
    id: 14,
    skill_id: 1,
    max_level: 30,
    type: "skill",
    name: "Strength 30",
    image_name: "Strength_icon.webp",
    isUnlocked: false,
    isComplete: false,
  },
];
